framework:
    secret: '%env(APP_SECRET)%'  # Clé secrète utilisée pour la sécurité de l'application
    # Activer la protection CSRF pour les formulaires
    csrf_protection: true

    # Activer la gestion des sessions et définir la durée de vie des sessions (10 minutes)
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_httponly: true
        gc_maxlifetime: 600

    # Optionnel : ESI et fragments pour des techniques de mise en cache avancées
    # esi: true
    # fragments: true

when@test:
    framework:
        test: true  # Activer les options de test
        session:
            storage_factory_id: session.storage.factory.mock_file  # Utiliser un stockage de session fictif pour les tests
