controllers:
    resource: ../src/Controller/
    type: attribute

admin_dashboard:
    path: /admin/dashboard
    defaults: { _controller: App\Controller\AdminController::dashboard }
    methods: [GET]

student_dashboard:
    path: /admin/dashboard
    defaults: { _controller: App\Controller\StudentController::dashboard }
    methods: [GET]

user_show:
    path: /user/
    controller: App\Controller\UserController::show
    methods: GET

app_reset_password_request:
    path: /reset-password
    controller: App\Controller\SecurityController::resetPasswordRequest

