# config/services.yaml

parameters:
    image_directory: '%kernel.project_dir%/public/uploads'  # Répertoire pour stocker les images

services:
    # Listener pour gérer l'expiration de session
    App\EventListener\SessionExpirationListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }  # Écoute l'événement de requête pour vérifier l'expiration de la session

    # Configuration par défaut pour les services dans *ce* fichier
    _defaults:
        autowire: true      # Injection automatique des dépendances dans vos services.
        autoconfigure: true # Enregistrement automatique de vos services en tant que commandes, abonnés aux événements, etc.
        public: true        # Permet d'optimiser le conteneur en évitant de vérifier ces services lors de l'appel d'une méthode de service.

    # Crée un service par classe dont l'id est le nom de classe entièrement qualifié
    App\:
        resource: '../src/'  # Chemin vers les ressources de votre application
        exclude:
            - '../src/DependencyInjection/'  # Exclure le répertoire de DependencyInjection
            - '../src/Kernel.php'  # Exclure le fichier Kernel.php

    # Définition explicite du service pour le gestionnaire de succès de connexion
    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'  # Injection du service router
